export const GET_USER_TWEETS_START = 'GET_USER_TWEETS_START';
export const GET_USER_TWEETS_SUCCESS = 'GET_USER_TWEETS_SUCCESS';
export const GET_USER_TWEETS_FAILED = 'GET_USER_TWEETS_FAILED';
export const LOAD_MORE_TWEETS_START = 'LOAD_MORE_TWEETS_START';
export const LOAD_MORE_TWEETS_SUCCESS = 'LOAD_MORE_TWEETS_SUCCESS';
export const LOAD_MORE_TWEETS_FAILED = 'LOAD_MORE_TWEETS_FAILED';
export const RESET_ERROR = 'RESET_ERROR';
